require("dotenv").config();

const fs = require("fs");
const path = require("path");
const crypto = require("crypto");
const mongoose = require("mongoose");
const bcrypt = require("bcrypt");
const Product = require("./models/Product");
const User = require("./models/User");
const { upsertProductsBySlug, seedTier3Extras } = require("./seedExtras");
const { productImageUrl } = require("./utils/config");

function imageUrl(slug) {
  return productImageUrl(`${slug}.png`);
}

const products = [
  {
    slug: "haraaz-red",
    name: "Haraaz Red",
    displayName: "Haraaz Red · Udaini",
    description:
      "Natural Yemeni coffee with stone fruit, cardamom, and cocoa notes.",
    price: 21,
    sizeLabel: "340 g",
    roast: "Light",
    origin: "Yemen",
    process: "Natural",
    altitude: "2,100–2,300 m",
    altitudeM: 2100,
    caffeine: "full",
    varietal: "Udaini",
    agtron: 58,
    harvest: "Feb 2026",
    density: "0.71 g/ml",
    notes: ["stone fruit", "cardamom", "cocoa"],
    score: 83,
    inventory: 42,
    roastDate: "04 Sep 2026",
    category: "coffee",
    soldOut: false,
    tradeTier: true,
    grindDefault: "Whole bean",
    recipes: {
      filter: "18:290 · 96 °C · 2:45",
      ibrik: "7 g : 70 ml · 3 rises",
    },
    lotLine: "LOT 12 · HARAAZ, YEMEN · ROASTED 04 SEP 2026",
    processDetail: "Natural, rooftop",
    agtronLabel: "58 (medium)",
    cardMeta: "UDAINI · 2,100 m · NATURAL",
    cardMeta2: "AGTRON 58 · ROAST 04 SEP",
    homeTag: "LIGHT · 2,100 m",
    imageUrl: imageUrl("haraaz-red"),
  },
  {
    slug: "mokha-harasi",
    name: "Mokha Harasi",
    displayName: "Mokha Harasi",
    description:
      "Dark Yemeni coffee with date, smoke, and black tea notes.",
    price: 23,
    sizeLabel: "340 g",
    roast: "Dark",
    origin: "Yemen",
    process: "Natural",
    altitude: "1,800–1,950 m",
    altitudeM: 1900,
    caffeine: "full",
    varietal: "Harasi",
    agtron: 38,
    harvest: "Jan 2026",
    density: "0.68 g/ml",
    notes: ["date", "smoke", "black tea"],
    score: 84,
    inventory: 28,
    roastDate: "04 Sep 2026",
    category: "coffee",
    soldOut: false,
    tradeTier: true,
    grindDefault: "Whole bean",
    recipes: {
      filter: "18:280 · 94 °C · 3:10",
      ibrik: "8 g : 70 ml · 3 rises",
    },
    lotLine: "LOT 09 · MOKHA, YEMEN · ROASTED 04 SEP 2026",
    processDetail: "Natural, raised beds",
    agtronLabel: "38 (dark)",
    cardMeta: "HARASI · 1,900 m · NATURAL",
    cardMeta2: "AGTRON 38 · ROAST 04 SEP",
    homeTag: "DARK · 1,900 m",
    imageUrl: imageUrl("mokha-harasi"),
  },
  {
    slug: "dhikr-blend",
    name: "Dhikr Blend",
    displayName: "Dhikr Blend",
    description: "Dark Yemeni blend with cocoa, dried fig, and spice notes.",
    price: 19,
    sizeLabel: "340 g",
    roast: "Dark",
    origin: "Yemen",
    process: "Natural",
    altitude: "Blend",
    altitudeM: 1750,
    caffeine: "full",
    varietal: "Blend",
    agtron: 40,
    harvest: "2025–26",
    density: "0.69 g/ml",
    notes: ["cocoa", "dried fig", "spice"],
    score: 82,
    inventory: 64,
    roastDate: "04 Sep 2026",
    category: "coffee",
    soldOut: false,
    tradeTier: true,
    grindDefault: "Espresso",
    recipes: {
      filter: "16:250 · 94 °C · 3:00",
      ibrik: "7 g : 70 ml · 3 rises",
    },
    lotLine: "BLEND · YEMEN LOTS · ROASTED 04 SEP 2026",
    processDetail: "Natural blend",
    agtronLabel: "40 (dark)",
    cardMeta: "BLEND · HOUSE DARK",
    cardMeta2: "AGTRON 40 · ROAST 04 SEP",
    homeTag: "DARK · BLEND",
    imageUrl: imageUrl("dhikr-blend"),
  },
  {
    slug: "qishr",
    name: "Qishr",
    displayName: "Qishr",
    description:
      "Traditional dried coffee-cherry husk brewed with ginger and spices.",
    price: 14,
    sizeLabel: "200 g",
    roast: "Husk",
    origin: "Yemen",
    process: "Natural",
    altitude: "—",
    altitudeM: 0,
    caffeine: "low",
    varietal: "Cherry husk",
    agtron: null,
    harvest: "Feb 2026",
    density: "—",
    notes: ["ginger", "cinnamon", "husk tea"],
    score: 80,
    inventory: 90,
    roastDate: "Sealed tin",
    category: "husk",
    soldOut: false,
    tradeTier: false,
    grindDefault: null,
    recipes: {
      filter: "12 g : 300 ml · 96 °C · 6:00",
      ibrik: "10 g : 80 ml · simmer",
    },
    lotLine: "CHERRY HUSK · CAFF-FREE · SEALED TIN",
    processDetail: "Dried husk, spiced",
    agtronLabel: "—",
    cardMeta: "CHERRY HUSK · CAFF-FREE",
    cardMeta2: "200 g · SEALED TIN",
    homeTag: "HUSK · 200 g",
    imageUrl: imageUrl("qishr"),
  },
  {
    slug: "dawairi-lot-04",
    name: "Dawairi Lot 04",
    displayName: "Dawairi Lot 04",
    description:
      "Washed Yemeni coffee with jasmine, white grape, and lime notes.",
    price: 26,
    sizeLabel: "340 g",
    roast: "Light",
    origin: "Yemen",
    process: "Washed",
    altitude: "2,300–2,450 m",
    altitudeM: 2400,
    caffeine: "full",
    varietal: "Dawairi",
    agtron: 62,
    harvest: "Mar 2026",
    density: "0.73 g/ml",
    notes: ["jasmine", "white grape", "lime"],
    score: 86,
    inventory: 18,
    roastDate: "04 Sep 2026",
    category: "coffee",
    soldOut: false,
    tradeTier: true,
    grindDefault: "Whole bean",
    recipes: {
      filter: "18:300 · 96 °C · 2:50",
      ibrik: "7 g : 70 ml · 3 rises",
    },
    lotLine: "LOT 04 · DAWAIRI, YEMEN · ROASTED 04 SEP 2026",
    processDetail: "Washed, patio dried",
    agtronLabel: "62 (light)",
    cardMeta: "DAWAIRI · 2,400 m · WASHED",
    cardMeta2: "AGTRON 62 · ROAST 04 SEP",
    homeTag: "LIGHT · 2,400 m",
    imageUrl: imageUrl("dawairi-lot-04"),
  },
  {
    slug: "tuffahi-n7",
    name: "Tuffahi Nº 7",
    displayName: "Tuffahi Nº 7",
    description:
      "Natural Yemeni coffee with apple, honey, and bergamot notes.",
    price: 24,
    sizeLabel: "340 g",
    roast: "Medium",
    origin: "Yemen",
    process: "Natural",
    altitude: "1,950–2,050 m",
    altitudeM: 2000,
    caffeine: "full",
    varietal: "Tuffahi",
    agtron: 60,
    harvest: "Feb 2026",
    density: "0.70 g/ml",
    notes: ["apple", "honey", "bergamot"],
    score: 85,
    inventory: 22,
    roastDate: "28 Aug 2026",
    category: "coffee",
    soldOut: false,
    tradeTier: true,
    grindDefault: "Whole bean",
    recipes: {
      filter: "18:290 · 95 °C · 2:55",
      ibrik: "7 g : 70 ml · 3 rises",
    },
    lotLine: "Nº 7 · TUFFAHI, YEMEN · ROASTED 28 AUG 2026",
    processDetail: "Natural, rooftop",
    agtronLabel: "60 (medium)",
    cardMeta: "TUFFAHI · 2,000 m · NATURAL",
    cardMeta2: "AGTRON 60 · ROAST 28 AUG",
    homeTag: "MEDIUM · 2,000 m",
    imageUrl: imageUrl("tuffahi-n7"),
  },
  {
    slug: "sanaa-espresso",
    name: "Sana'a Espresso",
    displayName: "Sana'a Espresso",
    description:
      "Yemeni espresso blend, omni-roast, with cocoa, walnut, and molasses notes.",
    price: 20,
    sizeLabel: "340 g",
    roast: "Medium",
    origin: "Yemen",
    process: "Blend",
    altitude: "Blend",
    altitudeM: 1700,
    caffeine: "full",
    varietal: "Blend",
    agtron: 42,
    harvest: "2025–26",
    density: "0.69 g/ml",
    notes: ["cocoa", "walnut", "molasses"],
    score: 83,
    inventory: 55,
    roastDate: "04 Sep 2026",
    category: "coffee",
    soldOut: false,
    tradeTier: true,
    grindDefault: "Espresso",
    recipes: {
      filter: "omni · 1:16",
      ibrik: "7 g : 70 ml · 3 rises",
    },
    lotLine: "OMNI ROAST · SANAʿA BLEND · ROASTED 04 SEP 2026",
    processDetail: "Blend, omni roast",
    agtronLabel: "42 (omni)",
    cardMeta: "BLEND · OMNI ROAST",
    cardMeta2: "5 KG TIER AVAILABLE",
    homeTag: "MEDIUM · OMNI",
    imageUrl: imageUrl("sanaa-espresso"),
  },
  {
    slug: "haraaz-n2",
    name: "Haraaz Nº 2",
    displayName: "Haraaz Nº 2",
    description:
      "Medium-roast Yemeni coffee with apricot and floral notes.",
    price: 22,
    sizeLabel: "340 g",
    roast: "Medium",
    origin: "Yemen",
    process: "Natural",
    altitude: "2,150–2,250 m",
    altitudeM: 2200,
    caffeine: "full",
    varietal: "Udaini",
    agtron: 61,
    harvest: "Feb 2026",
    density: "0.72 g/ml",
    notes: ["apricot", "florals"],
    score: 84,
    inventory: 0,
    roastDate: "18 Sep 2026",
    category: "coffee",
    soldOut: true,
    tradeTier: true,
    grindDefault: "Whole bean",
    recipes: {
      filter: "18:290 · 96 °C · 2:45",
      ibrik: "7 g : 70 ml · 3 rises",
    },
    lotLine: "SOLD OUT · NEXT ROAST 18 SEP 2026",
    processDetail: "Natural, rooftop",
    agtronLabel: "61 (light)",
    cardMeta: "SOLD OUT · NEXT ROAST 18 SEP",
    cardMeta2: "WAITLIST OPEN",
    homeTag: "MEDIUM · SOLD OUT",
    imageUrl: imageUrl("haraaz-n2"),
  },
  {
    slug: "bani-matar-honey",
    name: "Bani Matar Honey",
    displayName: "Bani Matar Honey",
    description:
      "Honey-process Yemeni coffee with honey, stone fruit, and almond notes.",
    price: 22,
    sizeLabel: "340 g",
    roast: "Medium",
    origin: "Yemen",
    process: "Honey",
    altitude: "1,800–1,900 m",
    altitudeM: 1850,
    caffeine: "full",
    varietal: "Udaini",
    agtron: 55,
    harvest: "Feb 2026",
    density: "0.70 g/ml",
    notes: ["honey", "stone fruit", "almond"],
    score: 84,
    inventory: 31,
    roastDate: "28 Aug 2026",
    category: "coffee",
    soldOut: false,
    tradeTier: true,
    grindDefault: "Whole bean",
    recipes: {
      filter: "18:285 · 95 °C · 3:00",
      ibrik: "7 g : 70 ml · 3 rises",
    },
    lotLine: "LOT 03 · BANI MATAR, YEMEN · ROASTED 28 AUG 2026",
    processDetail: "Honey process",
    agtronLabel: "55 (medium)",
    cardMeta: "UDAINI · 1,850 m · HONEY",
    cardMeta2: "AGTRON 55 · ROAST 28 AUG",
    homeTag: "MEDIUM · 1,850 m",
    imageUrl: imageUrl("bani-matar-honey"),
  },
  {
    slug: "yirgacheffe-lot-08",
    name: "Yirgacheffe Lot 08",
    displayName: "Yirgacheffe Lot 08",
    description:
      "Washed Ethiopian coffee with bergamot, peach, and jasmine notes.",
    price: 27,
    sizeLabel: "340 g",
    roast: "Light",
    origin: "Ethiopia",
    process: "Washed",
    altitude: "1,900–2,000 m",
    altitudeM: 1950,
    caffeine: "full",
    varietal: "Heirloom",
    agtron: 64,
    harvest: "Dec 2025",
    density: "0.72 g/ml",
    notes: ["bergamot", "peach", "jasmine"],
    score: 86,
    inventory: 40,
    roastDate: "04 Sep 2026",
    category: "coffee",
    soldOut: false,
    tradeTier: true,
    grindDefault: "Whole bean",
    recipes: {
      filter: "15:250 · 96 °C · 2:40",
      ibrik: "6 g : 70 ml · 3 rises",
    },
    lotLine: "LOT 08 · YIRGACHEFFE, ETHIOPIA · ROASTED 04 SEP 2026",
    processDetail: "Washed",
    agtronLabel: "64 (light)",
    cardMeta: "HEIRLOOM · 1,950 m · WASHED",
    cardMeta2: "AGTRON 64 · ROAST 04 SEP",
    homeTag: "LIGHT · 1,950 m",
    imageUrl: imageUrl("yirgacheffe-lot-08"),
  },
  {
    slug: "sidamo-natural",
    name: "Sidamo Natural",
    displayName: "Sidamo Natural",
    description:
      "Natural Ethiopian coffee with blueberry, cocoa, and floral notes.",
    price: 25,
    sizeLabel: "340 g",
    roast: "Medium",
    origin: "Ethiopia",
    process: "Natural",
    altitude: "1,750–1,850 m",
    altitudeM: 1800,
    caffeine: "full",
    varietal: "Heirloom",
    agtron: 52,
    harvest: "Nov 2025",
    density: "0.68 g/ml",
    notes: ["blueberry", "cocoa", "florals"],
    score: 84,
    inventory: 36,
    roastDate: "28 Aug 2026",
    category: "coffee",
    soldOut: false,
    tradeTier: false,
    grindDefault: "Whole bean",
    recipes: {
      filter: "16:260 · 94 °C · 3:05",
      ibrik: "7 g : 70 ml · 3 rises",
    },
    lotLine: "SIDAMO, ETHIOPIA · ROASTED 28 AUG 2026",
    processDetail: "Natural, raised beds",
    agtronLabel: "52 (medium)",
    cardMeta: "HEIRLOOM · 1,800 m · NATURAL",
    cardMeta2: "AGTRON 52 · ROAST 28 AUG",
    homeTag: "MEDIUM · 1,800 m",
    imageUrl: imageUrl("sidamo-natural"),
  },
  {
    slug: "guji-honey",
    name: "Guji Honey",
    displayName: "Guji Honey",
    description:
      "Honey-process Ethiopian coffee with honeydew, citrus, and tea notes.",
    price: 28,
    sizeLabel: "340 g",
    roast: "Light",
    origin: "Ethiopia",
    process: "Honey",
    altitude: "2,000–2,100 m",
    altitudeM: 2050,
    caffeine: "full",
    varietal: "Heirloom",
    agtron: 56,
    harvest: "Dec 2025",
    density: "0.71 g/ml",
    notes: ["honeydew", "citrus", "tea"],
    score: 85,
    inventory: 24,
    roastDate: "04 Sep 2026",
    category: "coffee",
    soldOut: false,
    tradeTier: true,
    grindDefault: "Whole bean",
    recipes: {
      filter: "18:290 · 95 °C · 2:50",
      ibrik: "7 g : 70 ml · 3 rises",
    },
    lotLine: "GUJI, ETHIOPIA · ROASTED 04 SEP 2026",
    processDetail: "Honey process",
    agtronLabel: "56 (medium)",
    cardMeta: "HEIRLOOM · 2,050 m · HONEY",
    cardMeta2: "AGTRON 56 · ROAST 04 SEP",
    homeTag: "LIGHT · 2,050 m",
    imageUrl: imageUrl("guji-honey"),
  },
  {
    slug: "harrar-longberry",
    name: "Harrar Longberry",
    displayName: "Harrar Longberry",
    description:
      "Dark natural Ethiopian coffee with blueberry, wine, and earth notes.",
    price: 24,
    sizeLabel: "340 g",
    roast: "Dark",
    origin: "Ethiopia",
    process: "Natural",
    altitude: "1,650–1,750 m",
    altitudeM: 1700,
    caffeine: "full",
    varietal: "Longberry",
    agtron: 36,
    harvest: "Nov 2025",
    density: "0.67 g/ml",
    notes: ["blueberry", "wine", "earth"],
    score: 81,
    inventory: 19,
    roastDate: "28 Aug 2026",
    category: "coffee",
    soldOut: false,
    tradeTier: false,
    grindDefault: "Whole bean",
    recipes: {
      filter: "16:250 · 93 °C · 3:15",
      ibrik: "8 g : 70 ml · 3 rises",
    },
    lotLine: "HARRAR, ETHIOPIA · ROASTED 28 AUG 2026",
    processDetail: "Natural, sun-dried",
    agtronLabel: "36 (dark)",
    cardMeta: "LONGBERRY · 1,700 m · NATURAL",
    cardMeta2: "AGTRON 36 · ROAST 28 AUG",
    homeTag: "DARK · 1,700 m",
    imageUrl: imageUrl("harrar-longberry"),
  },
  {
    slug: "java-kayumas",
    name: "Java Kayumas",
    displayName: "Java Kayumas",
    description:
      "Dark washed Java coffee with cedar, cocoa, and brown sugar notes.",
    price: 20,
    sizeLabel: "340 g",
    roast: "Dark",
    origin: "Java",
    process: "Washed",
    altitude: "1,350–1,450 m",
    altitudeM: 1400,
    caffeine: "full",
    varietal: "Typica",
    agtron: 54,
    harvest: "Aug 2025",
    density: "0.70 g/ml",
    notes: ["cedar", "cocoa", "brown sugar"],
    score: 82,
    inventory: 33,
    roastDate: "28 Aug 2026",
    category: "coffee",
    soldOut: false,
    tradeTier: true,
    grindDefault: "Whole bean",
    recipes: {
      filter: "16:260 · 94 °C · 3:00",
      ibrik: "7 g : 70 ml · 3 rises",
    },
    lotLine: "KAYUMAS, JAVA · ROASTED 28 AUG 2026",
    processDetail: "Washed",
    agtronLabel: "54 (medium)",
    cardMeta: "TYPICA · 1,400 m · WASHED",
    cardMeta2: "AGTRON 54 · ROAST 28 AUG",
    homeTag: "DARK · 1,400 m",
    imageUrl: imageUrl("java-kayumas"),
  },
  {
    slug: "java-preanger",
    name: "Java Preanger",
    displayName: "Java Preanger",
    description:
      "Dark natural Java coffee with tobacco, spice, and cocoa notes.",
    price: 21,
    sizeLabel: "340 g",
    roast: "Dark",
    origin: "Java",
    process: "Natural",
    altitude: "1,200–1,300 m",
    altitudeM: 1250,
    caffeine: "full",
    varietal: "Typica",
    agtron: 50,
    harvest: "Jul 2025",
    density: "0.69 g/ml",
    notes: ["tobacco", "spice", "cocoa"],
    score: 81,
    inventory: 27,
    roastDate: "28 Aug 2026",
    category: "coffee",
    soldOut: false,
    tradeTier: false,
    grindDefault: "Whole bean",
    recipes: {
      filter: "16:250 · 93 °C · 3:10",
      ibrik: "7 g : 70 ml · 3 rises",
    },
    lotLine: "PREANGER, JAVA · ROASTED 28 AUG 2026",
    processDetail: "Natural, sun-dried",
    agtronLabel: "50 (medium)",
    cardMeta: "TYPICA · 1,250 m · NATURAL",
    cardMeta2: "AGTRON 50 · ROAST 28 AUG",
    homeTag: "DARK · 1,250 m",
    imageUrl: imageUrl("java-preanger"),
  },
  {
    slug: "filter-papers-100",
    name: "Filter papers ×100",
    displayName: "Filter papers ×100",
    description: "Bleached V60 / Kalita filter papers, pack of 100.",
    price: 9,
    sizeLabel: "×100",
    roast: "—",
    origin: "—",
    process: "—",
    altitude: "—",
    altitudeM: 0,
    caffeine: "none",
    varietal: "—",
    agtron: null,
    harvest: "—",
    density: "—",
    notes: ["V60", "Kalita"],
    score: null,
    inventory: 200,
    roastDate: "—",
    category: "gear",
    soldOut: false,
    tradeTier: false,
    grindDefault: null,
    recipes: { filter: "—", ibrik: "—" },
    lotLine: "V60 / KALITA · 100 SHEETS",
    processDetail: "—",
    agtronLabel: "—",
    cardMeta: "V60 · 100 SHEETS",
    cardMeta2: "BLEACHED",
    homeTag: "GEAR",
    imageUrl: imageUrl("filter-papers-100"),
  },
  {
    slug: "ibrik-copper-240",
    name: "Copper ibrik 240 ml",
    displayName: "Copper ibrik 240 ml",
    description: "Hammered copper ibrik with wood handle, 240 ml.",
    price: 42,
    sizeLabel: "240 ml",
    roast: "—",
    origin: "—",
    process: "—",
    altitude: "—",
    altitudeM: 0,
    caffeine: "none",
    varietal: "—",
    agtron: null,
    harvest: "—",
    density: "—",
    notes: ["ibrik", "qahwa"],
    score: null,
    inventory: 12,
    roastDate: "—",
    category: "gear",
    soldOut: false,
    tradeTier: false,
    grindDefault: null,
    recipes: { filter: "—", ibrik: "7 g : 70 ml · 3 rises" },
    lotLine: "HAMMERED COPPER · WOOD HANDLE",
    processDetail: "—",
    agtronLabel: "—",
    cardMeta: "240 ML · COPPER",
    cardMeta2: "WOOD HANDLE",
    homeTag: "GEAR",
    imageUrl: imageUrl("ibrik-copper-240"),
  },
  {
    slug: "bag-clips",
    name: "Bag clips ×4",
    displayName: "Bag clips ×4",
    description: "Stainless steel bag clips, set of 4.",
    price: 8,
    sizeLabel: "×4",
    roast: "—",
    origin: "—",
    process: "—",
    altitude: "—",
    altitudeM: 0,
    caffeine: "none",
    varietal: "—",
    agtron: null,
    harvest: "—",
    density: "—",
    notes: ["seal"],
    score: null,
    inventory: 80,
    roastDate: "—",
    category: "gear",
    soldOut: false,
    tradeTier: false,
    grindDefault: null,
    recipes: { filter: "—", ibrik: "—" },
    lotLine: "STAINLESS · 4 CLIPS",
    processDetail: "—",
    agtronLabel: "—",
    cardMeta: "STAINLESS · SET OF 4",
    cardMeta2: "KEEPS BAGS CLOSED",
    homeTag: "GEAR",
    imageUrl: imageUrl("bag-clips"),
  },
];

function randomPassword() {
  return crypto.randomBytes(12).toString("base64url");
}

async function upsertUser({ name, email, password, role }) {
  const hashedPassword = await bcrypt.hash(password, 10);
  await User.findOneAndUpdate(
    { email: email.toLowerCase() },
    {
      name,
      email: email.toLowerCase(),
      password: hashedPassword,
      role,
    },
    {
      upsert: true,
      new: true,
      setDefaultsOnInsert: true,
      runValidators: true,
    }
  );
}

async function seedDatabase() {
  try {
    await mongoose.connect(process.env.MONGO_URI);

    await upsertProductsBySlug(Product, products);
    await seedTier3Extras();

    const customerPassword = randomPassword();
    const adminPassword = randomPassword();

    await upsertUser({
      name: "Yusuf",
      email: "yusuf@qahwasupply.local",
      password: customerPassword,
      role: "customer",
    });

    await upsertUser({
      name: "Admin",
      email: "admin@qahwasupply.local",
      password: adminPassword,
      role: "admin",
    });

    const credPath = path.join(__dirname, ".seed-credentials.txt");
    const credBody = [
      "Qawah seed credentials — do not commit",
      "",
      "customer",
      "name: Yusuf",
      "email: yusuf@qahwasupply.local",
      `password: ${customerPassword}`,
      "role: customer",
      "",
      "admin",
      "name: Admin",
      "email: admin@qahwasupply.local",
      `password: ${adminPassword}`,
      "role: admin",
      "",
    ].join("\n");
    fs.writeFileSync(credPath, credBody, { encoding: "utf8", mode: 0o600 });

    console.log(`Upserted ${products.length} products plus categories and QAHWA10`);
    await mongoose.connection.close();
  } catch (error) {
    console.error("Seed error:", error.message);
    process.exit(1);
  }
}

seedDatabase();
