export const GRINDS = [
  "Whole bean",
  "Filter",
  "Espresso",
  "Ibrik / powder",
];

export const SIZES = [
  { id: "200g", label: "200 g", factor: 14 / 21 },
  { id: "340g", label: "340 g", factor: 1 },
  { id: "1kg", label: "1 kg", factor: 54 / 21 },
  { id: "5kg", label: "5 kg", factor: null, trade: true },
];

export function money(n, forceCents = false) {
  const v = Number(n) || 0;
  if (forceCents || Math.round(v * 100) % 100 !== 0) {
    return `$${v.toFixed(2)}`;
  }
  return `$${v.toFixed(0)}`;
}

export function sizePrice(lot, sizeId) {
  if (lot.category === "gear" || lot.category === "husk") {
    return lot.price;
  }
  const size = SIZES.find((s) => s.id === sizeId) || SIZES[1];
  if (size.trade) return null;
  return Math.round(lot.price * size.factor);
}

export function subscribePrice(price) {
  return Math.round(price * 0.85 * 100) / 100;
}

const LOT_DEFS = [
  {
    _id: "lot-haraaz-red",
    slug: "haraaz-red",
    story:
      "The Haraaz massif climbs in terraces so steep that most of the harvest still comes down by foot. The Udaini trees on these slopes are old, and nobody on the mountain quite agrees on who planted them. Cherries dry whole on rooftops, raked by hand through the afternoon and covered before the cold comes down. That slow rooftop drying is where the stone fruit comes from, and the cardamom note that trails it. We roast it light so the fruit stays at the front of the cup.",
    name: "Haraaz Red",
    price: 21,
    sizeLabel: "340 g",
    roast: "Light",
    origin: "Yemen",
    process: "Natural",
    altitude: "2,100–2,300 m",
    altitudeM: 2100,
    caffeine: "full",
    varietal: "Udaini",
    agtron: 58,
    harvest: "Feb 2026",
    density: "0.71 g/ml",
    notes: ["stone fruit", "cardamom", "cocoa"],
    score: 83,
    inventory: 42,
    roastDate: "04 Sep 2026",
    roastDateShort: "04 SEP",
    category: "coffee",
    soldOut: false,
    tradeTier: true,
    grindDefault: "Whole bean",
    recipes: {
      filter: "18:290 · 96 °C · 2:45",
      ibrik: "7 g : 70 ml · 3 rises",
    },
    lotLine: "LOT 12 · HARAAZ, YEMEN · ROASTED 04 SEP 2026",
    processDetail: "Natural, rooftop",
    agtronLabel: "58 (medium)",
    cardMeta: "UDAINI · 2,100 m · NATURAL",
    cardMeta2: "AGTRON 58 · ROAST 04 SEP",
    homeTag: "LIGHT · 2,100 m",
    displayName: "Haraaz Red · Udaini",
  },
  {
    _id: "lot-mokha-harasi",
    slug: "mokha-harasi",
    story:
      "Mokha gave its name to the entire trade, and the Harasi trees inland of the old port still make a cup shaped by the habits built around it. Picked in January, dried whole, and roasted darker than we take most Yemeni coffee, on purpose: the date sweetness holds its ground and a thread of smoke arrives behind it. Brew it strong and small. This is the lot our ibrik customers reorder most.",
    name: "Mokha Harasi",
    price: 23,
    sizeLabel: "340 g",
    roast: "Dark",
    origin: "Yemen",
    process: "Natural",
    altitude: "1,800–1,950 m",
    altitudeM: 1900,
    caffeine: "full",
    varietal: "Harasi",
    agtron: 38,
    harvest: "Jan 2026",
    density: "0.68 g/ml",
    notes: ["date", "smoke", "black tea"],
    score: 84,
    inventory: 28,
    roastDate: "04 Sep 2026",
    roastDateShort: "04 SEP",
    category: "coffee",
    soldOut: false,
    tradeTier: true,
    grindDefault: "Whole bean",
    recipes: {
      filter: "18:280 · 94 °C · 3:10",
      ibrik: "8 g : 70 ml · 3 rises",
    },
    lotLine: "LOT 09 · MOKHA, YEMEN · ROASTED 04 SEP 2026",
    processDetail: "Natural, raised beds",
    agtronLabel: "38 (dark)",
    cardMeta: "HARASI · 1,900 m · NATURAL",
    cardMeta2: "AGTRON 38 · ROAST 04 SEP",
    homeTag: "DARK · 1,900 m",
    displayName: "Mokha Harasi",
  },
  {
    _id: "lot-dhikr-blend",
    slug: "dhikr-blend",
    story:
      "Built for a room full of people rather than for a cupping table. We blend the Yemeni naturals that land in volumes too small for their own release, and roast them dark enough to stay recognisable through cardamom, sugar and a long pour. Cocoa first, dried fig underneath, spice at the finish. It is the pot that stays on after everyone has arrived.",
    name: "Dhikr Blend",
    price: 19,
    sizeLabel: "340 g",
    roast: "Dark",
    origin: "Yemen",
    process: "Natural",
    altitude: "Blend",
    altitudeM: 1750,
    caffeine: "full",
    varietal: "Blend",
    agtron: 40,
    harvest: "2025–26",
    density: "0.69 g/ml",
    notes: ["cocoa", "dried fig", "spice"],
    score: 82,
    inventory: 64,
    roastDate: "04 Sep 2026",
    roastDateShort: "04 SEP",
    category: "coffee",
    soldOut: false,
    tradeTier: true,
    grindDefault: "Espresso",
    recipes: {
      filter: "16:250 · 94 °C · 3:00",
      ibrik: "7 g : 70 ml · 3 rises",
    },
    lotLine: "BLEND · YEMEN LOTS · ROASTED 04 SEP 2026",
    processDetail: "Natural blend",
    agtronLabel: "40 (dark)",
    cardMeta: "BLEND · HOUSE DARK",
    cardMeta2: "AGTRON 40 · ROAST 04 SEP",
    homeTag: "DARK · BLEND",
    displayName: "Dhikr Blend",
  },
  {
    _id: "lot-qishr",
    slug: "qishr",
    story:
      "Before the bean was the drink, the husk was. Qishr is the dried shell of the coffee cherry, simmered with ginger and cinnamon and served hot and sweet, and across much of Yemen it never stopped being the everyday cup. There is almost no caffeine in it, which is why it belongs at the end of an evening rather than the start of a day. Simmer it properly. Steeping it like tea will get you coloured water and nothing else.",
    name: "Qishr",
    price: 14,
    sizeLabel: "200 g",
    roast: "Husk",
    origin: "Yemen",
    process: "Natural",
    altitude: "n/a",
    altitudeM: 0,
    caffeine: "low",
    varietal: "Cherry husk",
    agtron: null,
    harvest: "Feb 2026",
    density: "n/a",
    notes: ["ginger", "cinnamon", "husk tea"],
    score: 80,
    inventory: 90,
    roastDate: "Sealed tin",
    roastDateShort: "TIN",
    category: "husk",
    soldOut: false,
    tradeTier: false,
    grindDefault: null,
    recipes: {
      filter: "12 g : 300 ml · 96 °C · 6:00",
      ibrik: "10 g : 80 ml · simmer",
    },
    lotLine: "CHERRY HUSK · CAFF-FREE · SEALED TIN",
    processDetail: "Dried husk, spiced",
    agtronLabel: "n/a",
    cardMeta: "CHERRY HUSK · CAFF-FREE",
    cardMeta2: "200 g · SEALED TIN",
    homeTag: "HUSK · 200 g",
    displayName: "Qishr",
    sizes: [{ id: "200g", label: "200 g", price: 14 }],
  },
  {
    _id: "lot-dawairi-04",
    slug: "dawairi-lot-04",
    story:
      "Washed Yemeni coffee stays rare for an unromantic reason: the water it takes is not something most terraces can spare. This Dawairi lot comes from the highest ground we buy, above 2,300 m, where cherry ripens slowly enough to keep its acidity. Depulped the same day it was picked, then dried on patios under shade cloth. The result is unusually clean for the origin, with jasmine, white grape and a lime edge that holds to the last sip.",
    name: "Dawairi Lot 04",
    price: 26,
    sizeLabel: "340 g",
    roast: "Light",
    origin: "Yemen",
    process: "Washed",
    altitude: "2,300–2,450 m",
    altitudeM: 2400,
    caffeine: "full",
    varietal: "Dawairi",
    agtron: 62,
    harvest: "Mar 2026",
    density: "0.73 g/ml",
    notes: ["jasmine", "white grape", "lime"],
    score: 86,
    inventory: 18,
    roastDate: "04 Sep 2026",
    roastDateShort: "04 SEP",
    category: "coffee",
    soldOut: false,
    tradeTier: true,
    grindDefault: "Whole bean",
    recipes: {
      filter: "18:300 · 96 °C · 2:50",
      ibrik: "7 g : 70 ml · 3 rises",
    },
    lotLine: "LOT 04 · DAWAIRI, YEMEN · ROASTED 04 SEP 2026",
    processDetail: "Washed, patio dried",
    agtronLabel: "62 (light)",
    cardMeta: "DAWAIRI · 2,400 m · WASHED",
    cardMeta2: "AGTRON 62 · ROAST 04 SEP",
    homeTag: "LIGHT · 2,400 m",
    displayName: "Dawairi Lot 04",
  },
  {
    _id: "lot-tuffahi-7",
    slug: "tuffahi-n7",
    story:
      "Tuffahi means apple, and for once the varietal name is doing honest work. The trees sit just above 2,000 m on terraces that catch morning sun and lose it early, and the fruit that comes off them is crisp rather than jammy. Dried whole, then roasted medium, which is exactly where the honey and the bergamot sit before either one takes over.",
    name: "Tuffahi Nº 7",
    price: 24,
    sizeLabel: "340 g",
    roast: "Medium",
    origin: "Yemen",
    process: "Natural",
    altitude: "1,950–2,050 m",
    altitudeM: 2000,
    caffeine: "full",
    varietal: "Tuffahi",
    agtron: 60,
    harvest: "Feb 2026",
    density: "0.70 g/ml",
    notes: ["apple", "honey", "bergamot"],
    score: 85,
    inventory: 22,
    roastDate: "28 Aug 2026",
    roastDateShort: "28 AUG",
    category: "coffee",
    soldOut: false,
    tradeTier: true,
    grindDefault: "Whole bean",
    recipes: {
      filter: "18:290 · 95 °C · 2:55",
      ibrik: "7 g : 70 ml · 3 rises",
    },
    lotLine: "Nº 7 · TUFFAHI, YEMEN · ROASTED 28 AUG 2026",
    processDetail: "Natural, rooftop",
    agtronLabel: "60 (medium)",
    cardMeta: "TUFFAHI · 2,000 m · NATURAL",
    cardMeta2: "AGTRON 60 · ROAST 28 AUG",
    homeTag: "MEDIUM · 2,000 m",
    displayName: "Tuffahi Nº 7",
  },
  {
    _id: "lot-sanaa-espresso",
    slug: "sanaa-espresso",
    story:
      "An omni-roast built to survive milk without vanishing into it. Sana'a sits in a high basin ringed by mountains, and the lots we blend for this come from the terraces on all sides of it. Pulled at nine bars it gives cocoa and walnut with molasses in the finish; in a moka pot it goes rounder and sweeter. The only coffee here we have tuned for a machine rather than a hand pour.",
    name: "Sana'a Espresso",
    price: 20,
    sizeLabel: "340 g",
    roast: "Dark",
    origin: "Yemen",
    process: "Natural",
    altitude: "Blend",
    altitudeM: 1700,
    caffeine: "full",
    varietal: "Blend",
    agtron: 42,
    harvest: "2025–26",
    density: "0.69 g/ml",
    notes: ["cocoa", "walnut", "molasses"],
    score: 83,
    inventory: 55,
    roastDate: "04 Sep 2026",
    roastDateShort: "04 SEP",
    category: "coffee",
    soldOut: false,
    tradeTier: true,
    grindDefault: "Espresso",
    recipes: {
      filter: "omni · 1:16",
      ibrik: "7 g : 70 ml · 3 rises",
    },
    lotLine: "OMNI ROAST · SANAʿA BLEND · ROASTED 04 SEP 2026",
    processDetail: "Blend, omni roast",
    agtronLabel: "42 (omni)",
    cardMeta: "BLEND · OMNI ROAST",
    cardMeta2: "5 KG TIER AVAILABLE",
    homeTag: "DARK · OMNI",
    displayName: "Sana'a Espresso",
  },
  {
    _id: "lot-haraaz-2",
    slug: "haraaz-n2",
    story:
      "The same mountain as Haraaz Red, a different set of terraces, and a noticeably prettier cup. N2 sits perhaps fifty metres higher and faces east, so the cherry hangs longer and comes in lighter. Apricot and open florals rather than stone fruit and cocoa. It is a small lot every year, and when it is gone it does not return until the next February.",
    name: "Haraaz Nº 2",
    price: 22,
    sizeLabel: "340 g",
    roast: "Light",
    origin: "Yemen",
    process: "Natural",
    altitude: "2,150–2,250 m",
    altitudeM: 2200,
    caffeine: "full",
    varietal: "Udaini",
    agtron: 61,
    harvest: "Feb 2026",
    density: "0.72 g/ml",
    notes: ["apricot", "florals"],
    score: 84,
    inventory: 0,
    roastDate: "18 Sep 2026",
    roastDateShort: "18 SEP",
    category: "coffee",
    soldOut: true,
    tradeTier: true,
    grindDefault: "Whole bean",
    recipes: {
      filter: "18:290 · 96 °C · 2:45",
      ibrik: "7 g : 70 ml · 3 rises",
    },
    lotLine: "SOLD OUT · NEXT ROAST 18 SEP 2026",
    processDetail: "Natural, rooftop",
    agtronLabel: "61 (light)",
    cardMeta: "SOLD OUT · NEXT ROAST 18 SEP",
    cardMeta2: "WAITLIST OPEN",
    homeTag: "LIGHT · SOLD OUT",
    displayName: "Haraaz Nº 2",
  },
  {
    _id: "lot-bani-matar",
    slug: "bani-matar-honey",
    story:
      "Bani Matar is where the honey process makes the most sense to us: enough afternoon sun to dry the sticky mucilage quickly, and nights cold enough that it does not ferment past the point of being useful. The fruit layer is left on the seed and the beds are turned every hour through the first two days. Honey in the name and in the cup, stone fruit behind it, and a dry almond note at the very end.",
    name: "Bani Matar Honey",
    price: 22,
    sizeLabel: "340 g",
    roast: "Medium",
    origin: "Yemen",
    process: "Honey",
    altitude: "1,800–1,900 m",
    altitudeM: 1850,
    caffeine: "full",
    varietal: "Udaini",
    agtron: 55,
    harvest: "Feb 2026",
    density: "0.70 g/ml",
    notes: ["honey", "stone fruit", "almond"],
    score: 84,
    inventory: 31,
    roastDate: "28 Aug 2026",
    roastDateShort: "28 AUG",
    category: "coffee",
    soldOut: false,
    tradeTier: true,
    grindDefault: "Whole bean",
    recipes: {
      filter: "18:285 · 95 °C · 3:00",
      ibrik: "7 g : 70 ml · 3 rises",
    },
    lotLine: "LOT 03 · BANI MATAR, YEMEN · ROASTED 28 AUG 2026",
    processDetail: "Honey process",
    agtronLabel: "55 (medium)",
    cardMeta: "UDAINI · 1,850 m · HONEY",
    cardMeta2: "AGTRON 55 · ROAST 28 AUG",
    homeTag: "MEDIUM · 1,850 m",
    displayName: "Bani Matar Honey",
  },
  {
    _id: "lot-yirgacheffe-08",
    slug: "yirgacheffe-lot-08",
    story:
      "The coffee that taught most people what washed Ethiopian is supposed to taste like. Heirloom varietals nobody has fully catalogued, grown on smallholdings measured in hundreds of trees rather than hectares, delivered to a shared washing station and dried on raised beds. Bergamot arrives first, then peach, then jasmine sitting over the top of both. Lot 08 is the cleanest of this season's arrivals.",
    name: "Yirgacheffe Lot 08",
    price: 18,
    sizeLabel: "340 g",
    roast: "Light",
    origin: "Ethiopia",
    process: "Washed",
    altitude: "1,900–2,000 m",
    altitudeM: 1950,
    caffeine: "full",
    varietal: "Heirloom",
    agtron: 64,
    harvest: "Dec 2025",
    density: "0.72 g/ml",
    notes: ["bergamot", "peach", "jasmine"],
    score: 86,
    inventory: 40,
    roastDate: "04 Sep 2026",
    roastDateShort: "04 SEP",
    category: "coffee",
    soldOut: false,
    tradeTier: true,
    grindDefault: "Whole bean",
    recipes: {
      filter: "15:250 · 96 °C · 2:40",
      ibrik: "6 g : 70 ml · 3 rises",
    },
    lotLine: "LOT 08 · YIRGACHEFFE, ETHIOPIA · ROASTED 04 SEP 2026",
    processDetail: "Washed",
    agtronLabel: "64 (light)",
    cardMeta: "HEIRLOOM · 1,950 m · WASHED",
    cardMeta2: "AGTRON 64 · ROAST 04 SEP",
    homeTag: "LIGHT · 1,950 m",
    displayName: "Yirgacheffe Lot 08",
  },
  {
    _id: "lot-sidamo-natural",
    slug: "sidamo-natural",
    story:
      "Naturals from Sidamo are the reason people started arguing about whether fruit this loud belongs in coffee at all. Whole cherries dry in the sun for close to three weeks, turned constantly, and the sugars in the fruit work their way into the seed. Blueberry so distinct it reads as deliberate, cocoa underneath it, florals around the edge. We roast to medium to keep it from tipping into something winey.",
    name: "Sidamo Natural",
    price: 17,
    sizeLabel: "340 g",
    roast: "Medium",
    origin: "Ethiopia",
    process: "Natural",
    altitude: "1,750–1,850 m",
    altitudeM: 1800,
    caffeine: "full",
    varietal: "Heirloom",
    agtron: 52,
    harvest: "Nov 2025",
    density: "0.68 g/ml",
    notes: ["blueberry", "cocoa", "florals"],
    score: 84,
    inventory: 36,
    roastDate: "28 Aug 2026",
    roastDateShort: "28 AUG",
    category: "coffee",
    soldOut: false,
    tradeTier: false,
    grindDefault: "Whole bean",
    recipes: {
      filter: "16:260 · 94 °C · 3:05",
      ibrik: "7 g : 70 ml · 3 rises",
    },
    lotLine: "SIDAMO, ETHIOPIA · ROASTED 28 AUG 2026",
    processDetail: "Natural, raised beds",
    agtronLabel: "52 (medium)",
    cardMeta: "HEIRLOOM · 1,800 m · NATURAL",
    cardMeta2: "AGTRON 52 · ROAST 28 AUG",
    homeTag: "MEDIUM · 1,800 m",
    displayName: "Sidamo Natural",
  },
  {
    _id: "lot-guji-honey",
    slug: "guji-honey",
    story:
      "Guji sits high enough, and separately enough, that it behaves like its own origin rather than a corner of Sidamo. This is a honey lot from around 2,000 m: the skin comes off, the sticky layer stays on, and the whole thing dries slowly on beds. Honeydew and citrus up front, and a thin tea-like body that gets better as the cup cools, which is the opposite of what most coffee does.",
    name: "Guji Honey",
    price: 19,
    sizeLabel: "340 g",
    roast: "Medium",
    origin: "Ethiopia",
    process: "Honey",
    altitude: "2,000–2,100 m",
    altitudeM: 2050,
    caffeine: "full",
    varietal: "Heirloom",
    agtron: 56,
    harvest: "Dec 2025",
    density: "0.71 g/ml",
    notes: ["honeydew", "citrus", "tea"],
    score: 85,
    inventory: 24,
    roastDate: "04 Sep 2026",
    roastDateShort: "04 SEP",
    category: "coffee",
    soldOut: false,
    tradeTier: true,
    grindDefault: "Whole bean",
    recipes: {
      filter: "18:290 · 95 °C · 2:50",
      ibrik: "7 g : 70 ml · 3 rises",
    },
    lotLine: "GUJI, ETHIOPIA · ROASTED 04 SEP 2026",
    processDetail: "Honey process",
    agtronLabel: "56 (medium)",
    cardMeta: "HEIRLOOM · 2,050 m · HONEY",
    cardMeta2: "AGTRON 56 · ROAST 04 SEP",
    homeTag: "MEDIUM · 2,050 m",
    displayName: "Guji Honey",
  },
  {
    _id: "lot-harrar",
    slug: "harrar-longberry",
    story:
      "Harrar is dry-processed out of necessity rather than fashion, in a region where water is the scarce input. The Longberry bean is unmistakable in the hand: long, pointed and gloriously uneven, which makes it a nuisance to roast evenly and worth the trouble anyway. Blueberry and wine over something earthy underneath. Taken dark, which is how it has always been drunk close to where it grows.",
    name: "Harrar Longberry",
    price: 18,
    sizeLabel: "340 g",
    roast: "Dark",
    origin: "Ethiopia",
    process: "Natural",
    altitude: "1,650–1,750 m",
    altitudeM: 1700,
    caffeine: "full",
    varietal: "Longberry",
    agtron: 36,
    harvest: "Nov 2025",
    density: "0.67 g/ml",
    notes: ["blueberry", "wine", "earth"],
    score: 81,
    inventory: 19,
    roastDate: "28 Aug 2026",
    roastDateShort: "28 AUG",
    category: "coffee",
    soldOut: false,
    tradeTier: false,
    grindDefault: "Whole bean",
    recipes: {
      filter: "16:250 · 93 °C · 3:15",
      ibrik: "8 g : 70 ml · 3 rises",
    },
    lotLine: "HARRAR, ETHIOPIA · ROASTED 28 AUG 2026",
    processDetail: "Natural, sun-dried",
    agtronLabel: "36 (dark)",
    cardMeta: "LONGBERRY · 1,700 m · NATURAL",
    cardMeta2: "AGTRON 36 · ROAST 28 AUG",
    homeTag: "DARK · 1,700 m",
    displayName: "Harrar Longberry",
  },
  {
    _id: "lot-java-kayumas",
    slug: "java-kayumas",
    story:
      "Typica survived on Java after leaf rust took it out of almost everywhere else, and the trees on the Kayumas slopes are descended from that stubborn population. Washed and dried on open patios in the dry season, at altitudes far lower than the East African lots on this shelf. Cedar, cocoa and brown sugar, with low acidity and a heavy body. This is what we hand people who tell us they do not like light roasts.",
    name: "Java Kayumas",
    price: 16,
    sizeLabel: "340 g",
    roast: "Medium",
    origin: "Java",
    process: "Washed",
    altitude: "1,350–1,450 m",
    altitudeM: 1400,
    caffeine: "full",
    varietal: "Typica",
    agtron: 54,
    harvest: "Aug 2025",
    density: "0.70 g/ml",
    notes: ["cedar", "cocoa", "brown sugar"],
    score: 82,
    inventory: 33,
    roastDate: "28 Aug 2026",
    roastDateShort: "28 AUG",
    category: "coffee",
    soldOut: false,
    tradeTier: true,
    grindDefault: "Whole bean",
    recipes: {
      filter: "16:260 · 94 °C · 3:00",
      ibrik: "7 g : 70 ml · 3 rises",
    },
    lotLine: "KAYUMAS, JAVA · ROASTED 28 AUG 2026",
    processDetail: "Washed",
    agtronLabel: "54 (medium)",
    cardMeta: "TYPICA · 1,400 m · WASHED",
    cardMeta2: "AGTRON 54 · ROAST 28 AUG",
    homeTag: "MEDIUM · 1,400 m",
    displayName: "Java Kayumas",
  },
  {
    _id: "lot-java-preanger",
    slug: "java-preanger",
    story:
      "Preanger is the older name for the highlands south of Bandung, and it turns up on shipping documents a century before it turns up on menus. Honey-processed here, which is unusual for the region and softens the edges considerably. Tobacco and warm spice sitting over cocoa. Grown lower than the Kayumas and noticeably rounder for it.",
    name: "Java Preanger",
    price: 16,
    sizeLabel: "340 g",
    roast: "Medium",
    origin: "Java",
    process: "Honey",
    altitude: "1,200–1,300 m",
    altitudeM: 1250,
    caffeine: "full",
    varietal: "Typica",
    agtron: 50,
    harvest: "Jul 2025",
    density: "0.69 g/ml",
    notes: ["tobacco", "spice", "cocoa"],
    score: 81,
    inventory: 27,
    roastDate: "28 Aug 2026",
    roastDateShort: "28 AUG",
    category: "coffee",
    soldOut: false,
    tradeTier: false,
    grindDefault: "Whole bean",
    recipes: {
      filter: "16:250 · 93 °C · 3:10",
      ibrik: "7 g : 70 ml · 3 rises",
    },
    lotLine: "PREANGER, JAVA · ROASTED 28 AUG 2026",
    processDetail: "Honey process",
    agtronLabel: "50 (medium)",
    cardMeta: "TYPICA · 1,250 m · HONEY",
    cardMeta2: "AGTRON 50 · ROAST 28 AUG",
    homeTag: "MEDIUM · 1,250 m",
    displayName: "Java Preanger",
  },
  {
    _id: "lot-filter-papers",
    slug: "filter-papers-100",
    story:
      "Bleached tabbed papers cut for 02-size V60 and Kalita Wave brewers, a hundred to a box. Bleached rather than natural because unbleached paper needs a longer rinse to stop tasting of itself. Rinse them anyway: it seats the paper against the cone and warms the brewer at the same time.",
    name: "Filter papers ×100",
    price: 9,
    sizeLabel: "×100",
    roast: "n/a",
    origin: "n/a",
    process: "n/a",
    altitude: "n/a",
    altitudeM: 0,
    caffeine: "none",
    varietal: "n/a",
    agtron: null,
    harvest: "n/a",
    density: "n/a",
    notes: ["V60", "Kalita"],
    score: null,
    inventory: 200,
    roastDate: "n/a",
    roastDateShort: "n/a",
    category: "gear",
    soldOut: false,
    tradeTier: false,
    grindDefault: null,
    recipes: { filter: "n/a", ibrik: "n/a" },
    lotLine: "V60 / KALITA · 100 SHEETS",
    processDetail: "n/a",
    agtronLabel: "n/a",
    cardMeta: "V60 · 100 SHEETS",
    cardMeta2: "BLEACHED",
    homeTag: "GEAR",
    displayName: "Filter papers ×100",
    placeholder: "img",
  },
  {
    _id: "lot-ibrik-copper",
    slug: "ibrik-copper-240",
    story:
      "Hand-hammered copper, tinned on the inside, 240 ml to the rim, which is two small cups with room for the foam to climb. Copper because it responds to a change in heat almost immediately, and the three rises that make qahwa work are a matter of pulling the pot off the flame at the right second. The tin lining needs redoing every few years. That is normal.",
    name: "Copper ibrik 240 ml",
    price: 48,
    sizeLabel: "240 ml",
    roast: "n/a",
    origin: "n/a",
    process: "n/a",
    altitude: "n/a",
    altitudeM: 0,
    caffeine: "none",
    varietal: "n/a",
    agtron: null,
    harvest: "n/a",
    density: "n/a",
    notes: ["ibrik", "qahwa"],
    score: null,
    inventory: 12,
    roastDate: "n/a",
    roastDateShort: "n/a",
    category: "gear",
    soldOut: false,
    tradeTier: false,
    grindDefault: null,
    recipes: { filter: "n/a", ibrik: "7 g : 70 ml · 3 rises" },
    lotLine: "HAMMERED COPPER · WOOD HANDLE",
    processDetail: "n/a",
    agtronLabel: "n/a",
    cardMeta: "240 ML · COPPER",
    cardMeta2: "WOOD HANDLE",
    homeTag: "GEAR",
    displayName: "Copper ibrik 240 ml",
    placeholder: "img",
  },
  {
    _id: "lot-bag-clips",
    slug: "bag-clips",
    story:
      "Four steel clips, wide enough to close a 340 g bag across the whole fold and stiff enough to keep it there. Coffee goes stale from oxygen far faster than from time, so the valve on the bag is only half the job. Fold the bag over twice, then clip it. Unglamorous, and it buys you another week of the coffee you paid for.",
    name: "Bag clips ×4",
    price: 6,
    sizeLabel: "×4",
    roast: "n/a",
    origin: "n/a",
    process: "n/a",
    altitude: "n/a",
    altitudeM: 0,
    caffeine: "none",
    varietal: "n/a",
    agtron: null,
    harvest: "n/a",
    density: "n/a",
    notes: ["seal"],
    score: null,
    inventory: 80,
    roastDate: "n/a",
    roastDateShort: "n/a",
    category: "gear",
    soldOut: false,
    tradeTier: false,
    grindDefault: null,
    recipes: { filter: "n/a", ibrik: "n/a" },
    lotLine: "STAINLESS · 4 CLIPS",
    processDetail: "n/a",
    agtronLabel: "n/a",
    cardMeta: "STAINLESS · SET OF 4",
    cardMeta2: "KEEPS BAGS CLOSED",
    homeTag: "GEAR",
    displayName: "Bag clips ×4",
    placeholder: "img",
  },
];

/*
 * Attach each lot's catalogue image, which ships in frontend/public/products
 * named after the lot's slug. Applied here rather than repeated on all 18
 * objects, so the two can never drift apart.
 *
 * This matters beyond tidiness: mergeWithApi falls back to these definitions
 * when the API is unreachable, and takes `hit.imageUrl || lot.imageUrl`.
 * Without an imageUrl here, an API outage turned every product card into a
 * grey placeholder rather than degrading to the real photo with mock pricing.
 */
export const LOTS = LOT_DEFS.map((lot) => ({
  ...lot,
  imageUrl: lot.imageUrl || (lot.slug ? `/products/${lot.slug}.png` : ""),
}));


export function getLot(id) {
  return LOTS.find((lot) => lot._id === id || lot.slug === id);
}

export function shopLots() {
  return LOTS.filter((lot) => lot.category === "coffee" || lot.category === "husk");
}

export function gearLots() {
  return LOTS.filter((lot) => lot.category === "gear");
}

export function inStockLots() {
  return shopLots().filter((lot) => !lot.soldOut);
}

export function mergeWithApi(apiProducts) {
  if (!Array.isArray(apiProducts) || apiProducts.length === 0) return LOTS;
  return LOTS.map((lot) => {
    const hit = apiProducts.find(
      (p) =>
        p &&
        typeof p.name === "string" &&
        p.name.toLowerCase() === lot.name.toLowerCase()
    );
    if (!hit) return lot;
    return {
      ...lot,
      mockId: lot._id,
      _id: hit._id || lot._id,
      price: typeof hit.price === "number" ? hit.price : lot.price,
      inventory:
        typeof hit.inventory === "number" ? hit.inventory : lot.inventory,
      soldOut:
        typeof hit.soldOut === "boolean"
          ? hit.soldOut
          : typeof hit.inventory === "number"
            ? hit.inventory <= 0
            : lot.soldOut,
      category: hit.category || lot.category,
      story: hit.story || lot.story,
      imageUrl: hit.imageUrl || lot.imageUrl,
      images: Array.isArray(hit.images) && hit.images.length ? hit.images : lot.images,
      roast: hit.roast || lot.roast,
      origin: hit.origin || lot.origin,
      notes: Array.isArray(hit.notes) ? hit.notes : lot.notes,
      slug: hit.slug || lot.slug,
    };
  });
}

export const HOME_ROAST = [
  "lot-haraaz-red",
  "lot-mokha-harasi",
  "lot-dhikr-blend",
  "lot-qishr",
];

export const ORDER_AGAIN = [
  { id: "lot-haraaz-red", last: "15 AUG", label: "Haraaz Red 340 g" },
  { id: "lot-filter-papers", last: "15 AUG", label: "Filter papers ×100" },
  { id: "lot-qishr", last: "01 AUG", label: "Qishr 200 g" },
];
